basePath: /api
definitions:
  entity.Deploy:
    properties:
      domain:
        type: string
      server_id:
        type: string
    type: object
  model.CreateTargetRequest:
    properties:
      ip:
        type: string
      name:
        type: string
    type: object
  model.Homsta:
    properties:
      blogName:
        type: string
      createdAt:
        type: string
      dbname:
        type: string
      dbusage:
        type: string
      description:
        type: string
      discUsage:
        type: string
      domain:
        type: string
      id:
        type: integer
      industry:
        type: string
      mailUsage:
        type: string
      path:
        type: string
      server:
        type: string
      siteURL:
        type: string
      updatedAt:
        type: string
      users:
        type: string
    type: object
  model.Status:
    enum:
    - unknown
    - initialize
    - check_view
    - check_japan
    - crawl_comp_info
    - pending_output
    - done
    - trash
    type: string
    x-enum-varnames:
    - StatusUnknown
    - StatusInitialize
    - StatusCheckView
    - StatusCheckJapan
    - StatusCrawlCompInfo
    - StatusPendingOutput
    - StatusDone
    - StatusTrash
  model.Target:
    properties:
      created_at:
        type: string
      currentPage:
        type: integer
      id:
        type: integer
      ip:
        type: string
      lastFetchedAt:
        type: string
      lastFullScanAt:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/model.TargetStatus'
      updated_at:
        type: string
    type: object
  model.TargetStatus:
    enum:
    - init
    - fetched
    - disabled
    type: string
    x-enum-varnames:
    - TargetStatusInit
    - TargetStatusFetched
    - TargetStatusDisabled
  model.UpdateTargetRequest:
    properties:
      ip:
        type: string
      name:
        type: string
    type: object
  request.DeployRequest:
    properties:
      dst:
        items:
          $ref: '#/definitions/entity.Deploy'
        type: array
      src:
        $ref: '#/definitions/entity.Deploy'
    type: object
  request.Homsta:
    properties:
      blogName:
        type: string
      dbUsage:
        type: string
      description:
        type: string
      discUsage:
        type: string
      path:
        type: string
      siteUrl:
        type: string
      users:
        type: string
    type: object
  request.UpdateDomain:
    properties:
      address:
        type: string
      can_view:
        type: boolean
      company:
        type: string
      industry:
        type: string
      is_japan:
        type: boolean
      is_send:
        type: boolean
      is_ssl:
        type: boolean
      landline_phone:
        type: string
      mobile_phone:
        type: string
      name:
        type: string
      owner_id:
        type: string
      page_num:
        type: integer
      phone:
        type: string
      prefecture:
        type: string
      president:
        type: string
      raw_page:
        type: string
      status:
        $ref: '#/definitions/model.Status'
      target:
        type: string
      title:
        type: string
    type: object
  response.Domain:
    properties:
      address:
        type: string
      can_view:
        type: boolean
      company:
        type: string
      created_at:
        type: string
      id:
        type: integer
      industry:
        type: string
      is_japan:
        type: boolean
      is_send:
        type: boolean
      is_ssl:
        type: boolean
      landline_phone:
        type: string
      mobile_phone:
        type: string
      name:
        type: string
      owner_id:
        type: string
      page_num:
        type: integer
      phone:
        type: string
      prefecture:
        type: string
      president:
        type: string
      raw_page:
        type: string
      status:
        $ref: '#/definitions/model.Status'
      target:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.Domains:
    properties:
      count:
        type: integer
      domains:
        items:
          $ref: '#/definitions/response.Domain'
        type: array
      total:
        type: integer
    type: object
info:
  contact: {}
  description: ドメイン管理API
  title: Sales API
  version: "1.0"
paths:
  /backup:
    post:
      consumes:
      - application/json
      description: Polling domain information
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      summary: Backup domains
      tags:
      - Domains
  /domains:
    get:
      consumes:
      - application/json
      description: Get domain list
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: ドメイン名
        in: query
        name: name
        type: string
      - description: 閲覧可能か
        in: query
        name: can_view
        type: boolean
      - description: 日本のサイトか
        in: query
        name: is_japan
        type: boolean
      - description: mapsで問い合わせページを開いたか
        in: query
        name: is_send
        type: boolean
      - description: owner_id
        in: query
        name: owner_id
        type: string
      - description: ステータス
        in: query
        name: status
        type: string
      - description: 業種
        in: query
        name: industry
        type: string
      - description: SSL対応可否
        in: query
        name: is_ssl
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Domains'
            type: array
      summary: Get domains
      tags:
      - ドメイン
  /domains/{id}:
    delete:
      consumes:
      - application/json
      description: Delete domain by name
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete domain
      tags:
      - ドメイン
    get:
      consumes:
      - application/json
      description: Get domain
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Domain'
      summary: Get domain
      tags:
      - ドメイン
    put:
      consumes:
      - application/json
      description: Update domain information
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新ドメイン情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateDomain'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Domain'
      summary: Update domain
      tags:
      - ドメイン
  /domains/analyze:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: サイトの情報を解析する
      tags:
      - ドメイン
  /external/analyze/domains:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Homstaの業種を判別します
      tags:
      - Homsta
  /external/assort:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      security:
      - BearerAuth: []
      summary: ワードプレスを整理し、スプレッドシートに出力します
      tags:
      - Wordpress
  /external/deploy:
    post:
      consumes:
      - application/json
      parameters:
      - description: デプロイ情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DeployRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      security:
      - BearerAuth: []
      summary: ワードプレスをデプロイします
      tags:
      - Wordpress
  /external/deploy/one:
    post:
      consumes:
      - application/json
      parameters:
      - description: デプロイ情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DeployRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      security:
      - BearerAuth: []
      summary: ワードプレスを一件デプロイします
      tags:
      - Wordpress
  /external/fetch/domains:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: ストラテジードライブサーバーにあるドメインフォルダ一覧を取得します。
      tags:
      - Wordpress
  /external/fetch/domains/detail:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: ストラテジードライブサーバーにあるドメインの詳細情報を取得します
      tags:
      - Wordpress
  /external/output/domains:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Homstaの業種を判別します
      tags:
      - Homsta
  /fetch:
    post:
      consumes:
      - application/json
      description: Fetch domain information from target
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      summary: Fetch domains
      tags:
      - ViewDNS
  /growth/analyze:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - ドメイン
  /growth/fetch:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - ドメイン
  /growth/output:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - ドメイン
  /growth/polling:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      tags:
      - ドメイン
  /homsta:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: ストラテジードライブサーバーにあるWordPressの情報を整理します
      tags:
      - Wordpress
  /homstas:
    get:
      consumes:
      - application/json
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Homsta'
            type: array
      summary: Homsta一覧を取得します
      tags:
      - Homsta
    post:
      consumes:
      - application/json
      parameters:
      - description: Homsta情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Homsta'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Homstaを作成します
      tags:
      - Homsta
  /homstas/{name}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Homsta'
      summary: Homstaを取得します
      tags:
      - Homsta
  /polling:
    post:
      consumes:
      - application/json
      description: Polling domain information
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      summary: Polling domains
      tags:
      - Domains
  /targets:
    get:
      consumes:
      - application/json
      description: Get target list
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Target'
            type: array
      summary: Get targets
      tags:
      - ターゲット
    post:
      consumes:
      - application/json
      description: Create new target
      parameters:
      - description: 作成ターゲット情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateTargetRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Target'
      summary: Create target
      tags:
      - ターゲット
  /targets/{id}:
    delete:
      consumes:
      - application/json
      description: Delete target by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete target
      tags:
      - ターゲット
    put:
      consumes:
      - application/json
      description: Update target information
      parameters:
      - description: 更新ターゲット情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateTargetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Target'
      summary: Update target
      tags:
      - ターゲット
  /webhook/analyze:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: PubSubのwebhookエンドポイント
      tags:
      - ドメイン
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
