basePath: /api
definitions:
  entity.Deploy:
    properties:
      domain:
        type: string
      server_id:
        type: string
    type: object
  model.CreateTargetRequest:
    properties:
      ip:
        type: string
      name:
        type: string
    type: object
  model.CreateTaskRequest:
    properties:
      description:
        type: string
      name:
        type: string
      status:
        type: integer
    type: object
  model.PostFetchRequest:
    properties:
      target:
        type: string
    required:
    - target
    type: object
  model.Status:
    enum:
    - unknown
    - initialize
    - check_view
    - check_japan
    - crawl_comp_info
    - done
    - trash
    type: string
    x-enum-varnames:
    - StatusUnknown
    - StatusInitialize
    - StatusCheckView
    - StatusCheckJapan
    - StatusCrawlCompInfo
    - StatusDone
    - StatusTrash
  model.Target:
    properties:
      created_at:
        type: string
      id:
        type: integer
      ip:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/model.TargetStatus'
      updated_at:
        type: string
    type: object
  model.TargetStatus:
    enum:
    - init
    - fetched
    type: string
    x-enum-varnames:
    - TargetStatusInit
    - TargetStatusFetched
  model.Task:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
      updated_at:
        type: string
    type: object
  model.UpdateTargetRequest:
    properties:
      ip:
        type: string
      name:
        type: string
    type: object
  model.UpdateTaskRequest:
    properties:
      description:
        type: string
      name:
        type: string
      status:
        type: integer
    type: object
  request.CreateLog:
    properties:
      category:
        type: string
      message:
        type: string
      name:
        type: string
    type: object
  request.DeployRequest:
    properties:
      dst:
        items:
          $ref: '#/definitions/entity.Deploy'
        type: array
      src:
        $ref: '#/definitions/entity.Deploy'
    type: object
  request.UpdateDomain:
    properties:
      address:
        type: string
      can_view:
        type: boolean
      company:
        type: string
      industry:
        type: string
      is_japan:
        type: boolean
      is_send:
        type: boolean
      is_ssl:
        type: boolean
      landline_phone:
        type: string
      mobile_phone:
        type: string
      name:
        type: string
      owner_id:
        type: string
      page_num:
        type: integer
      phone:
        type: string
      prefecture:
        type: string
      president:
        type: string
      raw_page:
        type: string
      status:
        $ref: '#/definitions/model.Status'
      target:
        type: string
      title:
        type: string
    type: object
  response.Domain:
    properties:
      address:
        type: string
      can_view:
        type: boolean
      company:
        type: string
      created_at:
        type: string
      id:
        type: integer
      industry:
        type: string
      is_japan:
        type: boolean
      is_send:
        type: boolean
      is_ssl:
        type: boolean
      landline_phone:
        type: string
      mobile_phone:
        type: string
      name:
        type: string
      owner_id:
        type: string
      page_num:
        type: integer
      phone:
        type: string
      prefecture:
        type: string
      president:
        type: string
      raw_page:
        type: string
      status:
        $ref: '#/definitions/model.Status'
      target:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.Domains:
    properties:
      count:
        type: integer
      domains:
        items:
          $ref: '#/definitions/response.Domain'
        type: array
      total:
        type: integer
    type: object
  response.Log:
    properties:
      category:
        type: string
      created_at:
        type: string
      message:
        type: string
      name:
        type: string
    type: object
  response.Logs:
    properties:
      count:
        type: integer
      logs:
        items:
          $ref: '#/definitions/response.Log'
        type: array
      total:
        type: integer
    type: object
info:
  contact: {}
  description: Type "Bearer" followed by a space and JWT token.
  title: Sales API
  version: "1.0"
paths:
  /domains:
    get:
      consumes:
      - application/json
      description: Get domain list
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      - description: ドメイン名
        in: query
        name: name
        type: string
      - description: 閲覧可能か
        in: query
        name: can_view
        type: boolean
      - description: 日本のサイトか
        in: query
        name: is_japan
        type: boolean
      - description: mapsで問い合わせページを開いたか
        in: query
        name: is_send
        type: boolean
      - description: owner_id
        in: query
        name: owner_id
        type: string
      - description: ステータス
        in: query
        name: status
        type: string
      - description: 業種
        in: query
        name: industry
        type: string
      - description: SSL対応可否
        in: query
        name: is_ssl
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Domains'
            type: array
      summary: Get domains
      tags:
      - ドメイン
  /domains/{id}:
    delete:
      consumes:
      - application/json
      description: Delete domain by name
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete domain
      tags:
      - ドメイン
    get:
      consumes:
      - application/json
      description: Get domain
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Domain'
      summary: Get domain
      tags:
      - ドメイン
    put:
      consumes:
      - application/json
      description: Update domain information
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: 更新ドメイン情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateDomain'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Domain'
      summary: Update domain
      tags:
      - ドメイン
  /domains/analyze:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: サイトの情報を解析する
      tags:
      - ドメイン
  /domains/output:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: スプレッドシートに出力する
      tags:
      - ドメイン
  /external/api/assort:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: ワードプレスを整理し、スプレッドシートに出力します
      tags:
      - Wordpress
  /external/api/deploy:
    post:
      consumes:
      - application/json
      parameters:
      - description: デプロイ情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.DeployRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: ワードプレスをデプロイします
      tags:
      - Wordpress
  /fetch:
    post:
      consumes:
      - application/json
      description: Fetch domain information from target
      parameters:
      - description: Fetch request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.PostFetchRequest'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
      summary: Fetch domains
      tags:
      - ViewDNS
  /logs:
    get:
      consumes:
      - application/json
      description: Get log list
      parameters:
      - description: 処理名
        in: query
        name: name
        type: string
      - description: カテゴリー
        in: query
        name: category
        type: string
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Logs'
            type: array
      summary: Get logs
      tags:
      - ログ
    post:
      consumes:
      - application/json
      description: Create new log
      parameters:
      - description: 作成ログ情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateLog'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Log'
      summary: Create log
      tags:
      - ログ
  /targets:
    get:
      consumes:
      - application/json
      description: Get target list
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Target'
            type: array
      summary: Get targets
      tags:
      - ターゲット
    post:
      consumes:
      - application/json
      description: Create new target
      parameters:
      - description: 作成ターゲット情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateTargetRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Target'
      summary: Create target
      tags:
      - ターゲット
  /targets/{id}:
    delete:
      consumes:
      - application/json
      description: Delete target by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete target
      tags:
      - ターゲット
    put:
      consumes:
      - application/json
      description: Update target information
      parameters:
      - description: 更新ターゲット情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateTargetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Target'
      summary: Update target
      tags:
      - ターゲット
  /tasks:
    get:
      consumes:
      - application/json
      description: Get task list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
      summary: Get tasks
      tags:
      - タスク
    post:
      consumes:
      - application/json
      description: Create new task
      parameters:
      - description: 作成タスク情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Task'
      summary: Create task
      tags:
      - タスク
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task by id
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete task
      tags:
      - タスク
    put:
      consumes:
      - application/json
      description: Update task information
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: 更新タスク情報
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
      summary: Update task
      tags:
      - タスク
  /tasks/{id}/execute:
    post:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: タスクを実行します
      tags:
      - タスク
  /tasks/execute:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: 全てのタスクを実行します
      tags:
      - タスク
swagger: "2.0"
